### ISSUE TITLE
Low GPS when using in Linux

### ISSUE THREAD

**Issue by garyyu** [mozkomor/GrinGoldMiner#16]
With my `GTX 1070 Ti`, I run GrinGoldMiner in Linux (Ubuntu x86_64):

```
./Theta -d 0 -a 192.168.1.129
```
I only got `2.47 GPS`, which is far below the ever reported `3.2 GPS` for GTX 1070 Ti.  And the `edges` folder already mount by ramdisk.

What could be the possible reason for this lower performance? 
I would like a compare with Windows version, but unfortunately I don't have windows machine to test at this moment.

```
Graphs: 1400, Trims: 1400, Shares: 33, Mined: 1
Graphs per Solution: 42
GPS(Graphs/Second): 2.47
```
`Theta` is built with https://github.com/mozkomor/GrinGoldMiner/pull/15 for `GPS` report.

**Comment by garyyu** [comment]
Compared with `grin-miner`, on same 1070 Ti, the reported GPS is 2.90, that is `17%` advantage.

What's the main root cause for this `17%` lossing of GGM?

**Comment by phooton** [comment]
See here https://github.com/mozkomor/GrinGoldMiner/issues/2

The optimization is known since April. It is relatively simple, but I'm no longer updating cuda solvers, because OpenCL is just as fast and universal. It runs faster, but also consumes more energy while running, so cuda solvers in this repo are just fine for testnet purposes.
