### ISSUE TITLE
Not switching to secondary pool address

### ISSUE THREAD

**Issue by nerdatwork** [mozkomor/GrinGoldMiner#62]
After grinmint's stratum issue I noticed GGM isn't switching to secondary pool. Are there any number of retries set before it switches to secondary pool ?

**Comment by urza** [comment]
Looking at the logs, the issues is with the grinmint behaviour. After connection is lost, miner starts reconnecting and Grinmint ACCEPTS this connection. But then drops the connection immediately again. They should either not accept the connection and or start sending jobs. I suspect they have divived their architecture in layers, and only one layer failed, while the other (accepting connections) kept working.

We could try detecting this.. or maybe connect to random (primary/backup) first when reconnecting...

**Comment by theREALeson** [comment]
Note this same thing happens with MWgrinpool as primary connection, they just had issues and rigs did not switch over to Grinmint.

**Comment by urza** [comment]
I created 2.8 beta2 that chooses randomly where to re-connect (either primary or backup pool) in case connection is lost. This should solve it because sooner or later you will hit the one that is stable.

Does not affect starting miner, there still primary is first.

 If you want to help test this, download 2.8 beta2 file under latest release
